In [1]:
import pandas as pd

In [4]:
data=pd.read_csv("marks..csv")

In [5]:
data

name  hrs  marks
0  harshith    3     30
1       cnu    5     50
2       dev    8     80
3       ram    2     20
4     sunny    1     10
5     kylie    4     40

In [7]:
y=data["marks"]

In [10]:
X=data["hrs"]

In [14]:
type(X)

pandas.core.series.Series

In [15]:
import numpy as np

In [16]:
X = X.values

In [17]:
type(X)

numpy.ndarray

In [18]:
X.shape

(6,)

In [20]:
X=X.reshape(6,1)

In [21]:
X.shape

(6, 1)

In [22]:
X

array([[3],
       [5],
       [8],
       [2],
       [1],
       [4]], dtype=int64)

In [23]:
from sklearn.linear_model import LinearRegression

In [25]:
mind=LinearRegression()

In [26]:
mind

LinearRegression()

In [28]:
mind1=mind.fit(X,y)

In [29]:
mind1.predict([[8]])

array([80.])

In [30]:
mind1.coef_

array([10.])

In [31]:
import joblib

In [32]:
joblib.dump(mind1,"marks")

['marks']